// Code generated by mockery v1.0.0. DO NOT EDIT.

package adaptersmocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/magneticio/vamp-cloud-cli/cmd/models"

// VampCloudServicesClient is an autogenerated mock type for the VampCloudServicesClient type
type VampCloudServicesClient struct {
	mock.Mock
}

// GetService provides a mock function with given fields: name
func (_m *VampCloudServicesClient) GetService(name string) (*models.Service, error) {
	ret := _m.Called(name)

	var r0 *models.Service
	if rf, ok := ret.Get(0).(func(string) *models.Service); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceVersionByID provides a mock function with given fields: id
func (_m *VampCloudServicesClient) GetServiceVersionByID(id int64) (string, error) {
	ret := _m.Called(id)

	var r0 string
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServices provides a mock function with given fields:
func (_m *VampCloudServicesClient) ListServices() ([]models.Service, error) {
	ret := _m.Called()

	var r0 []models.Service
	if rf, ok := ret.Get(0).(func() []models.Service); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
