// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/magneticio/vamp-cloud-cli/models"
)

// GetApplicationsIDIngressesReader is a Reader for the GetApplicationsIDIngresses structure.
type GetApplicationsIDIngressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationsIDIngressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationsIDIngressesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetApplicationsIDIngressesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetApplicationsIDIngressesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetApplicationsIDIngressesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetApplicationsIDIngressesOK creates a GetApplicationsIDIngressesOK with default headers values
func NewGetApplicationsIDIngressesOK() *GetApplicationsIDIngressesOK {
	return &GetApplicationsIDIngressesOK{}
}

/*GetApplicationsIDIngressesOK handles this case with default header values.

List of ingress objects
*/
type GetApplicationsIDIngressesOK struct {
	Payload *models.Ingresses
}

func (o *GetApplicationsIDIngressesOK) Error() string {
	return fmt.Sprintf("[GET /applications/{id}/ingresses][%d] getApplicationsIdIngressesOK  %+v", 200, o.Payload)
}

func (o *GetApplicationsIDIngressesOK) GetPayload() *models.Ingresses {
	return o.Payload
}

func (o *GetApplicationsIDIngressesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Ingresses)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDIngressesUnauthorized creates a GetApplicationsIDIngressesUnauthorized with default headers values
func NewGetApplicationsIDIngressesUnauthorized() *GetApplicationsIDIngressesUnauthorized {
	return &GetApplicationsIDIngressesUnauthorized{}
}

/*GetApplicationsIDIngressesUnauthorized handles this case with default header values.

The requester is not authorized.
*/
type GetApplicationsIDIngressesUnauthorized struct {
	Payload *models.Error
}

func (o *GetApplicationsIDIngressesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{id}/ingresses][%d] getApplicationsIdIngressesUnauthorized  %+v", 401, o.Payload)
}

func (o *GetApplicationsIDIngressesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDIngressesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDIngressesInternalServerError creates a GetApplicationsIDIngressesInternalServerError with default headers values
func NewGetApplicationsIDIngressesInternalServerError() *GetApplicationsIDIngressesInternalServerError {
	return &GetApplicationsIDIngressesInternalServerError{}
}

/*GetApplicationsIDIngressesInternalServerError handles this case with default header values.

The server has encountered a situation it does not know how to handle.
*/
type GetApplicationsIDIngressesInternalServerError struct {
	Payload *models.Error
}

func (o *GetApplicationsIDIngressesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /applications/{id}/ingresses][%d] getApplicationsIdIngressesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetApplicationsIDIngressesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDIngressesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDIngressesDefault creates a GetApplicationsIDIngressesDefault with default headers values
func NewGetApplicationsIDIngressesDefault(code int) *GetApplicationsIDIngressesDefault {
	return &GetApplicationsIDIngressesDefault{
		_statusCode: code,
	}
}

/*GetApplicationsIDIngressesDefault handles this case with default header values.

Generic error.
*/
type GetApplicationsIDIngressesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get applications ID ingresses default response
func (o *GetApplicationsIDIngressesDefault) Code() int {
	return o._statusCode
}

func (o *GetApplicationsIDIngressesDefault) Error() string {
	return fmt.Sprintf("[GET /applications/{id}/ingresses][%d] GetApplicationsIDIngresses default  %+v", o._statusCode, o.Payload)
}

func (o *GetApplicationsIDIngressesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDIngressesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
