// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/magneticio/vamp-cloud-cli/models"
)

// GetApplicationsIDReader is a Reader for the GetApplicationsID structure.
type GetApplicationsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetApplicationsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetApplicationsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetApplicationsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetApplicationsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetApplicationsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetApplicationsIDOK creates a GetApplicationsIDOK with default headers values
func NewGetApplicationsIDOK() *GetApplicationsIDOK {
	return &GetApplicationsIDOK{}
}

/*GetApplicationsIDOK handles this case with default header values.

An application object.
*/
type GetApplicationsIDOK struct {
	Payload *models.Application
}

func (o *GetApplicationsIDOK) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdOK  %+v", 200, o.Payload)
}

func (o *GetApplicationsIDOK) GetPayload() *models.Application {
	return o.Payload
}

func (o *GetApplicationsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDUnauthorized creates a GetApplicationsIDUnauthorized with default headers values
func NewGetApplicationsIDUnauthorized() *GetApplicationsIDUnauthorized {
	return &GetApplicationsIDUnauthorized{}
}

/*GetApplicationsIDUnauthorized handles this case with default header values.

The requester is not authorized.
*/
type GetApplicationsIDUnauthorized struct {
	Payload *models.Error
}

func (o *GetApplicationsIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetApplicationsIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDForbidden creates a GetApplicationsIDForbidden with default headers values
func NewGetApplicationsIDForbidden() *GetApplicationsIDForbidden {
	return &GetApplicationsIDForbidden{}
}

/*GetApplicationsIDForbidden handles this case with default header values.

The requester does not have access rights to the resource.
*/
type GetApplicationsIDForbidden struct {
	Payload *models.Error
}

func (o *GetApplicationsIDForbidden) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdForbidden  %+v", 403, o.Payload)
}

func (o *GetApplicationsIDForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDNotFound creates a GetApplicationsIDNotFound with default headers values
func NewGetApplicationsIDNotFound() *GetApplicationsIDNotFound {
	return &GetApplicationsIDNotFound{}
}

/*GetApplicationsIDNotFound handles this case with default header values.

The server can not find the requested resource.
*/
type GetApplicationsIDNotFound struct {
	Payload *models.Error
}

func (o *GetApplicationsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdNotFound  %+v", 404, o.Payload)
}

func (o *GetApplicationsIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDInternalServerError creates a GetApplicationsIDInternalServerError with default headers values
func NewGetApplicationsIDInternalServerError() *GetApplicationsIDInternalServerError {
	return &GetApplicationsIDInternalServerError{}
}

/*GetApplicationsIDInternalServerError handles this case with default header values.

The server has encountered a situation it does not know how to handle.
*/
type GetApplicationsIDInternalServerError struct {
	Payload *models.Error
}

func (o *GetApplicationsIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] getApplicationsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetApplicationsIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetApplicationsIDDefault creates a GetApplicationsIDDefault with default headers values
func NewGetApplicationsIDDefault(code int) *GetApplicationsIDDefault {
	return &GetApplicationsIDDefault{
		_statusCode: code,
	}
}

/*GetApplicationsIDDefault handles this case with default header values.

Generic error.
*/
type GetApplicationsIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get applications ID default response
func (o *GetApplicationsIDDefault) Code() int {
	return o._statusCode
}

func (o *GetApplicationsIDDefault) Error() string {
	return fmt.Sprintf("[GET /applications/{id}][%d] GetApplicationsID default  %+v", o._statusCode, o.Payload)
}

func (o *GetApplicationsIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetApplicationsIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
