// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetApplicationsIDInstallationParams creates a new GetApplicationsIDInstallationParams object
// with the default values initialized.
func NewGetApplicationsIDInstallationParams() *GetApplicationsIDInstallationParams {
	var ()
	return &GetApplicationsIDInstallationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationsIDInstallationParamsWithTimeout creates a new GetApplicationsIDInstallationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationsIDInstallationParamsWithTimeout(timeout time.Duration) *GetApplicationsIDInstallationParams {
	var ()
	return &GetApplicationsIDInstallationParams{

		timeout: timeout,
	}
}

// NewGetApplicationsIDInstallationParamsWithContext creates a new GetApplicationsIDInstallationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationsIDInstallationParamsWithContext(ctx context.Context) *GetApplicationsIDInstallationParams {
	var ()
	return &GetApplicationsIDInstallationParams{

		Context: ctx,
	}
}

// NewGetApplicationsIDInstallationParamsWithHTTPClient creates a new GetApplicationsIDInstallationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationsIDInstallationParamsWithHTTPClient(client *http.Client) *GetApplicationsIDInstallationParams {
	var ()
	return &GetApplicationsIDInstallationParams{
		HTTPClient: client,
	}
}

/*GetApplicationsIDInstallationParams contains all the parameters to send to the API endpoint
for the get applications ID installation operation typically these are written to a http.Request
*/
type GetApplicationsIDInstallationParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) WithTimeout(timeout time.Duration) *GetApplicationsIDInstallationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) WithContext(ctx context.Context) *GetApplicationsIDInstallationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) WithHTTPClient(client *http.Client) *GetApplicationsIDInstallationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) WithID(id int64) *GetApplicationsIDInstallationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get applications ID installation params
func (o *GetApplicationsIDInstallationParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationsIDInstallationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
