// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetApplicationsIDIngressesParams creates a new GetApplicationsIDIngressesParams object
// with the default values initialized.
func NewGetApplicationsIDIngressesParams() *GetApplicationsIDIngressesParams {
	var ()
	return &GetApplicationsIDIngressesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationsIDIngressesParamsWithTimeout creates a new GetApplicationsIDIngressesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationsIDIngressesParamsWithTimeout(timeout time.Duration) *GetApplicationsIDIngressesParams {
	var ()
	return &GetApplicationsIDIngressesParams{

		timeout: timeout,
	}
}

// NewGetApplicationsIDIngressesParamsWithContext creates a new GetApplicationsIDIngressesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationsIDIngressesParamsWithContext(ctx context.Context) *GetApplicationsIDIngressesParams {
	var ()
	return &GetApplicationsIDIngressesParams{

		Context: ctx,
	}
}

// NewGetApplicationsIDIngressesParamsWithHTTPClient creates a new GetApplicationsIDIngressesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationsIDIngressesParamsWithHTTPClient(client *http.Client) *GetApplicationsIDIngressesParams {
	var ()
	return &GetApplicationsIDIngressesParams{
		HTTPClient: client,
	}
}

/*GetApplicationsIDIngressesParams contains all the parameters to send to the API endpoint
for the get applications ID ingresses operation typically these are written to a http.Request
*/
type GetApplicationsIDIngressesParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) WithTimeout(timeout time.Duration) *GetApplicationsIDIngressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) WithContext(ctx context.Context) *GetApplicationsIDIngressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) WithHTTPClient(client *http.Client) *GetApplicationsIDIngressesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) WithID(id int64) *GetApplicationsIDIngressesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get applications ID ingresses params
func (o *GetApplicationsIDIngressesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationsIDIngressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
