// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/magneticio/vamp-cloud-cli/models"
)

// PostApplicationsIDIngressesReader is a Reader for the PostApplicationsIDIngresses structure.
type PostApplicationsIDIngressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostApplicationsIDIngressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostApplicationsIDIngressesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostApplicationsIDIngressesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostApplicationsIDIngressesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostApplicationsIDIngressesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPostApplicationsIDIngressesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostApplicationsIDIngressesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostApplicationsIDIngressesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostApplicationsIDIngressesOK creates a PostApplicationsIDIngressesOK with default headers values
func NewPostApplicationsIDIngressesOK() *PostApplicationsIDIngressesOK {
	return &PostApplicationsIDIngressesOK{}
}

/*PostApplicationsIDIngressesOK handles this case with default header values.

ID of created ingress
*/
type PostApplicationsIDIngressesOK struct {
	Payload *PostApplicationsIDIngressesOKBody
}

func (o *PostApplicationsIDIngressesOK) Error() string {
	return fmt.Sprintf("[POST /applications/{id}/ingresses][%d] postApplicationsIdIngressesOK  %+v", 200, o.Payload)
}

func (o *PostApplicationsIDIngressesOK) GetPayload() *PostApplicationsIDIngressesOKBody {
	return o.Payload
}

func (o *PostApplicationsIDIngressesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostApplicationsIDIngressesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplicationsIDIngressesBadRequest creates a PostApplicationsIDIngressesBadRequest with default headers values
func NewPostApplicationsIDIngressesBadRequest() *PostApplicationsIDIngressesBadRequest {
	return &PostApplicationsIDIngressesBadRequest{}
}

/*PostApplicationsIDIngressesBadRequest handles this case with default header values.

The request is invalid.
*/
type PostApplicationsIDIngressesBadRequest struct {
	Payload *models.Error
}

func (o *PostApplicationsIDIngressesBadRequest) Error() string {
	return fmt.Sprintf("[POST /applications/{id}/ingresses][%d] postApplicationsIdIngressesBadRequest  %+v", 400, o.Payload)
}

func (o *PostApplicationsIDIngressesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApplicationsIDIngressesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplicationsIDIngressesUnauthorized creates a PostApplicationsIDIngressesUnauthorized with default headers values
func NewPostApplicationsIDIngressesUnauthorized() *PostApplicationsIDIngressesUnauthorized {
	return &PostApplicationsIDIngressesUnauthorized{}
}

/*PostApplicationsIDIngressesUnauthorized handles this case with default header values.

The requester is not authorized.
*/
type PostApplicationsIDIngressesUnauthorized struct {
	Payload *models.Error
}

func (o *PostApplicationsIDIngressesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /applications/{id}/ingresses][%d] postApplicationsIdIngressesUnauthorized  %+v", 401, o.Payload)
}

func (o *PostApplicationsIDIngressesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApplicationsIDIngressesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplicationsIDIngressesForbidden creates a PostApplicationsIDIngressesForbidden with default headers values
func NewPostApplicationsIDIngressesForbidden() *PostApplicationsIDIngressesForbidden {
	return &PostApplicationsIDIngressesForbidden{}
}

/*PostApplicationsIDIngressesForbidden handles this case with default header values.

The requester does not have access rights to the resource.
*/
type PostApplicationsIDIngressesForbidden struct {
	Payload *models.Error
}

func (o *PostApplicationsIDIngressesForbidden) Error() string {
	return fmt.Sprintf("[POST /applications/{id}/ingresses][%d] postApplicationsIdIngressesForbidden  %+v", 403, o.Payload)
}

func (o *PostApplicationsIDIngressesForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApplicationsIDIngressesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplicationsIDIngressesConflict creates a PostApplicationsIDIngressesConflict with default headers values
func NewPostApplicationsIDIngressesConflict() *PostApplicationsIDIngressesConflict {
	return &PostApplicationsIDIngressesConflict{}
}

/*PostApplicationsIDIngressesConflict handles this case with default header values.

The request cannot be completed due to a conflict with the current state of the resource.
*/
type PostApplicationsIDIngressesConflict struct {
	Payload *models.Error
}

func (o *PostApplicationsIDIngressesConflict) Error() string {
	return fmt.Sprintf("[POST /applications/{id}/ingresses][%d] postApplicationsIdIngressesConflict  %+v", 409, o.Payload)
}

func (o *PostApplicationsIDIngressesConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApplicationsIDIngressesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplicationsIDIngressesInternalServerError creates a PostApplicationsIDIngressesInternalServerError with default headers values
func NewPostApplicationsIDIngressesInternalServerError() *PostApplicationsIDIngressesInternalServerError {
	return &PostApplicationsIDIngressesInternalServerError{}
}

/*PostApplicationsIDIngressesInternalServerError handles this case with default header values.

The server has encountered a situation it does not know how to handle.
*/
type PostApplicationsIDIngressesInternalServerError struct {
	Payload *models.Error
}

func (o *PostApplicationsIDIngressesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /applications/{id}/ingresses][%d] postApplicationsIdIngressesInternalServerError  %+v", 500, o.Payload)
}

func (o *PostApplicationsIDIngressesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApplicationsIDIngressesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplicationsIDIngressesDefault creates a PostApplicationsIDIngressesDefault with default headers values
func NewPostApplicationsIDIngressesDefault(code int) *PostApplicationsIDIngressesDefault {
	return &PostApplicationsIDIngressesDefault{
		_statusCode: code,
	}
}

/*PostApplicationsIDIngressesDefault handles this case with default header values.

Generic error.
*/
type PostApplicationsIDIngressesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post applications ID ingresses default response
func (o *PostApplicationsIDIngressesDefault) Code() int {
	return o._statusCode
}

func (o *PostApplicationsIDIngressesDefault) Error() string {
	return fmt.Sprintf("[POST /applications/{id}/ingresses][%d] PostApplicationsIDIngresses default  %+v", o._statusCode, o.Payload)
}

func (o *PostApplicationsIDIngressesDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostApplicationsIDIngressesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostApplicationsIDIngressesOKBody post applications ID ingresses o k body
swagger:model PostApplicationsIDIngressesOKBody
*/
type PostApplicationsIDIngressesOKBody struct {

	// The ingress ID
	ID int64 `json:"id,omitempty"`
}

// Validate validates this post applications ID ingresses o k body
func (o *PostApplicationsIDIngressesOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostApplicationsIDIngressesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostApplicationsIDIngressesOKBody) UnmarshalBinary(b []byte) error {
	var res PostApplicationsIDIngressesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
