// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/magneticio/vamp-cloud-cli/models"
)

// NewPostApplicationsIDIngressesParams creates a new PostApplicationsIDIngressesParams object
// with the default values initialized.
func NewPostApplicationsIDIngressesParams() *PostApplicationsIDIngressesParams {
	var ()
	return &PostApplicationsIDIngressesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostApplicationsIDIngressesParamsWithTimeout creates a new PostApplicationsIDIngressesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostApplicationsIDIngressesParamsWithTimeout(timeout time.Duration) *PostApplicationsIDIngressesParams {
	var ()
	return &PostApplicationsIDIngressesParams{

		timeout: timeout,
	}
}

// NewPostApplicationsIDIngressesParamsWithContext creates a new PostApplicationsIDIngressesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostApplicationsIDIngressesParamsWithContext(ctx context.Context) *PostApplicationsIDIngressesParams {
	var ()
	return &PostApplicationsIDIngressesParams{

		Context: ctx,
	}
}

// NewPostApplicationsIDIngressesParamsWithHTTPClient creates a new PostApplicationsIDIngressesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostApplicationsIDIngressesParamsWithHTTPClient(client *http.Client) *PostApplicationsIDIngressesParams {
	var ()
	return &PostApplicationsIDIngressesParams{
		HTTPClient: client,
	}
}

/*PostApplicationsIDIngressesParams contains all the parameters to send to the API endpoint
for the post applications ID ingresses operation typically these are written to a http.Request
*/
type PostApplicationsIDIngressesParams struct {

	/*ID*/
	ID int64
	/*Ingress
	  The application to create

	*/
	Ingress *models.Ingress

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) WithTimeout(timeout time.Duration) *PostApplicationsIDIngressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) WithContext(ctx context.Context) *PostApplicationsIDIngressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) WithHTTPClient(client *http.Client) *PostApplicationsIDIngressesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) WithID(id int64) *PostApplicationsIDIngressesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) SetID(id int64) {
	o.ID = id
}

// WithIngress adds the ingress to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) WithIngress(ingress *models.Ingress) *PostApplicationsIDIngressesParams {
	o.SetIngress(ingress)
	return o
}

// SetIngress adds the ingress to the post applications ID ingresses params
func (o *PostApplicationsIDIngressesParams) SetIngress(ingress *models.Ingress) {
	o.Ingress = ingress
}

// WriteToRequest writes these params to a swagger request
func (o *PostApplicationsIDIngressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if o.Ingress != nil {
		if err := r.SetBodyParam(o.Ingress); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
