// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ClusterInput cluster input
//
// swagger:model ClusterInput
type ClusterInput struct {

	// description
	Description string `json:"description,omitempty"`

	// name
	// Min Length: 1
	Name string `json:"name,omitempty"`

	// provider
	// Enum: [AKS DOKS EKS GKE SELF_MANAGED OTHER]
	Provider string `json:"provider,omitempty"`
}

// Validate validates this cluster input
func (m *ClusterInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvider(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterInput) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MinLength("name", "body", string(m.Name), 1); err != nil {
		return err
	}

	return nil
}

var clusterInputTypeProviderPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AKS","DOKS","EKS","GKE","SELF_MANAGED","OTHER"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		clusterInputTypeProviderPropEnum = append(clusterInputTypeProviderPropEnum, v)
	}
}

const (

	// ClusterInputProviderAKS captures enum value "AKS"
	ClusterInputProviderAKS string = "AKS"

	// ClusterInputProviderDOKS captures enum value "DOKS"
	ClusterInputProviderDOKS string = "DOKS"

	// ClusterInputProviderEKS captures enum value "EKS"
	ClusterInputProviderEKS string = "EKS"

	// ClusterInputProviderGKE captures enum value "GKE"
	ClusterInputProviderGKE string = "GKE"

	// ClusterInputProviderSELFMANAGED captures enum value "SELF_MANAGED"
	ClusterInputProviderSELFMANAGED string = "SELF_MANAGED"

	// ClusterInputProviderOTHER captures enum value "OTHER"
	ClusterInputProviderOTHER string = "OTHER"
)

// prop value enum
func (m *ClusterInput) validateProviderEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, clusterInputTypeProviderPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ClusterInput) validateProvider(formats strfmt.Registry) error {

	if swag.IsZero(m.Provider) { // not required
		return nil
	}

	// value enum
	if err := m.validateProviderEnum("provider", "body", m.Provider); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClusterInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterInput) UnmarshalBinary(b []byte) error {
	var res ClusterInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
