// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PolicySelectionStrategyInput policy selection strategy input
//
// swagger:model PolicySelectionStrategyInput
type PolicySelectionStrategyInput struct {

	// default policy ID
	DefaultPolicyID int64 `json:"defaultPolicyID,omitempty"`

	// major policy ID
	MajorPolicyID int64 `json:"majorPolicyID,omitempty"`

	// minor policy ID
	MinorPolicyID int64 `json:"minorPolicyID,omitempty"`

	// patch policy ID
	PatchPolicyID int64 `json:"patchPolicyID,omitempty"`
}

// Validate validates this policy selection strategy input
func (m *PolicySelectionStrategyInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolicySelectionStrategyInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicySelectionStrategyInput) UnmarshalBinary(b []byte) error {
	var res PolicySelectionStrategyInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
